### ISSUE TITLE
week 02 

### ISSUE THREAD

**Issue by KHajili98** [Elmira-tech/PragmatechCsharpProject#3]
1). tasklar isledikce gite elave olunsun, bu artiq verdish halina kecmelidir ki proyekt ishleyende cetinlik cekesiz.
2). Tapsiriq 1de:
     Person structin constructorunda int x telebi neye gore yazilib?  **Person(int x )**

**Comment by Elmira-tech** [comment]
1) Bir müddət daha taskların hamısını bir yerdə gitə atacam. Kodların sətir sayı hələki azdı deyə, bir yerdə atmaq işimi kompaktlaşdırır. Zamanla dediyiniz vərdiş özlüyündən formalaşacaq. 
2) int x tələbi ona görə qoyulub ki, person struct-nı çağıranda ona tam ədəd tanımlayacaqdım. Beləcə kodu run edəndə yuxardakı constructora gəlib həmin tələbi görüb constructorun içini oxuya bilir. (int x) deyil də (string x) da tanımlaya bilərdim. Onda da structı  çağıranda string bir dəyər verəcəkdim.

**Comment by KHajili98** [comment]
1. ozun bilersen nece isteyirsen ele edersen. Amma bele et deyiremse mueyyen sebebi vardir.
2. int x vermeyine ehtiyac yoxdur. constructorun icerisini oxuyur, int x o zaman vererdinki hemin x-i her hansi propertye menimsederdin (Tapsiriq 6da Age=age oldugu kimi). Yeni constructora her hansi parametr daxil etmeyin hec bir menasi yoxdur.

**Comment by Elmira-tech** [comment]
2. int x verməyəndə səhv götürür axı. Və şərti düzgün icra eləmir
